FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# E2EO

E2EO-NWRO REST API インターフェース

# Group <カタログ>

## カタログ【リソースID指定なし】 [/v1/nwro/catalogues]

### カタログ登録 [POST]

カタログ登録する

+ NSD(object) - NSDオブジェクトを渡す。

+ Request (application/json)

        {
        "question": "Favorite programming language?"
        }

+ Response 200 (application/json)

    + Headers
    
            Location: /questions/1
    
    + Body
    
            {
                "question": "Favorite programming language?",
                "is": "Ruby"
            }

## カタログ【リソースID指定あり】 [/vi/nwro/catalogues/{id}]

### カタログ変更 [PUT]
+ Response 200 (application/json)

### カタログ削除 [DELETE]
+ Response 200 (application/json)

## カタログ結果通知 [/v1/e2eo/catalogues/{id}]

### カタログ登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列

# Group <予約>

## リソース予約 [/v1/nwro-e2eo/reservation]

### リソース予約 [POST]

リソースを予約する。
cf. "NFVIFA(15)000435r10_IFA013_NS_Lifecycle_Mgmt_Operations.docx"

ここで"serviceAccessPoinsts"のkeyはNSDで定義されたCPを指す。
valueは基底リソース払い出しで登録されたobjectNaming形式の文字列である。
ただし、E2EOからVLAN-IDの指定がある場合はvalueの末尾にVLAN-IDが付加される。
VLAN-IDの指定がなければNWROが(WIMを経由して)適切なVLAN-IDを設定する。

+ 必要パラメータ: serviceAccessPoints, nsdId, flavourId

+ Request (application/json)

        {
            "asyncNotificationLocation": "/v1/e2eo-nwro/notifications", 
            "flavourId": "flvour-789", 
            "nsdId": "ns-001_v1.0", 
            "requestHeader": {
                "apiKey": "#aea57sjas6vsst4jwjol", 
                "functionType": 10, 
                "senderSystemId": "e2eo", 
                "sequenceNo": "12345"
            }, 
            "serviceAccessPoints": {
                "cp-03": "NMS=wim-01/EMS=ems/ME-ID=クラスタ番号+leafSW番号/rack=1/shelf=1/slot=1/subslot=1", 
                "cp-10": "NMS=wim-01/EMS=ems/ME-ID=クラスタ番号+leafSW番号/rack=1/shelf=1/slot=2/subslot=1"
            }
        }

+ Response 202 (application/json)

    + Body
    
            {
                "responseHeader": {
                "processCode": "000000",
                "processID": "xx1123456789012",
                "receivedDate": "2015/09/10 12:34:56",
                "sequenceNo": "12345"
                }
            }

## リソース予約完了通知 [/vi/e2eo-nwro/notifications]

### リソース予約完了通知 [POST]

リソース予約の完了後に完了通知を返却する。
返却する内容はNSR一式である。

+ 必要パラメータ: nsInfo

+ Request (application/json)

        {
            "nsInfo": {
                "audit_log": "",
                "auto_scale_policy": "",
                "connection_point": [
                    {
                        "id": "NMS=wim-01/EMS=ems/FRE=001",
                        "type": "vlan100"
                    },
                    {
                        "id": "NMS=wim-01/EMS=ems/FRE=002",
                        "type": "vlan200"
                    },
                    {
                        "id": "NMS=wim-01/EMS=ems/FRE=003",
                        "type": "vlan300"
                    }
                ],
                "descriptor_reference": "",
                "id": "nsr-123",
                "lifecycle_event": "",
                "lifecycle_event_history": "",
                "monitoring_parameter": "",
                "notification": "",
                "pnfr": [
                    {
                        "connected_virtual_link": "",
                        "connection_point": "",
                        "description": "",
                        "descriptor_reference": "",
                        "id": "pnfr-001",
                        "oam_reference": "",
                        "parent_ns": "nsr-123",
                        "pnf_address": "",
                        "vendor": "",
                        "version": "",
                        "vnffgr": ""
                    }
                ],
                "resource_reservation": "",
                "runtime_policy_info": "",
                "service_deployment_flavour": "",
                "status": "",
                "vendor": "",
                "version": "",
                "vlr": [
                    {
                        "allocated_capacity": "",
                        "audit_log": "",
                        "connection": [
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=001"
                            },
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=002"
                            }
                        ],
                        "connectivity_type": "",
                        "descriptor_reference": "",
                        "id": "vlr-001",
                        "leaf_requirement": "",
                        "lifecycle_event_history": "",
                        "notification": "",
                        "number_of_enpoints": "",
                        "parent_ns": "nsr-123",
                        "qos": "",
                        "root_requirement": "",
                        "status": "",
                        "test_access": "",
                        "vendor": "",
                        "version": "",
                        "vnffgr_reference": ""
                    },
                    {
                        "allocated_capacity": "",
                        "audit_log": "",
                        "connection": [
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=002"
                            },
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=003"
                            }
                        ],
                        "connectivity_type": "",
                        "descriptor_reference": "",
                        "id": "vlr-002",
                        "leaf_requirement": "",
                        "lifecycle_event_history": "",
                        "notification": "",
                        "number_of_enpoints": "",
                        "parent_ns": "nsr-123",
                        "qos": "",
                        "root_requirement": "",
                        "status": "",
                        "test_access": "",
                        "vendor": "",
                        "version": "",
                        "vnffgr_reference": ""
                    }
                ],
                "vnf_dependency": "",
                "vnffgr": [
                    {
                        "audit_log": "",
                        "connection_point": [
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=001"
                            },
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=002"
                            },
                            {
                                "id": "NMS=wim-01/EMS=ems/FRE=003"
                            }
                        ],
                        "dependent_virtual_link": "",
                        "descriptor_reference": "",
                        "id": "vnffgr-001",
                        "lifecycle_event_history": "",
                        "member_vnfs": "",
                        "network_forwarding_path": "",
                        "notification": "",
                        "number_of_endpoints": "",
                        "number_of_pnfs": "",
                        "number_of_virtual_links": "",
                        "number_of_vnfs": "",
                        "parent_ns": "nsr-123",
                        "status": "",
                        "vendor": "",
                        "version": ""
                    }
                ],
                "vnfr": [
                    {
                        "audit_log": "",
                        "auto_scale_policy": "",
                        "connected_external_virtual_link": "",
                        "connection_point": "",
                        "dependency": "",
                        "deployment_flavour": "",
                        "descriptor_reference": "",
                        "id": "vnfr-001",
                        "lifecycle_event": "",
                        "lifecycle_event_history": "",
                        "localization": "",
                        "monitoring_parameter": "",
                        "notification": "",
                        "parent_ns": "nsr-123",
                        "runtime_policy_info": "",
                        "status": "",
                        "vdu": "",
                        "vendor": "",
                        "version": "",
                        "virtual_link": "",
                        "vnf_address": "",
                        "vnfm_id": ""
                    }
                ]
            },
            "requestHeader": {
                "apiKey": "#aea57sjas6vsst4jwjol",
                "functionType": 20,
                "senderSystemId": "nwro1",
                "sequenceNo": "54321"
            },
            "resourceUri": "/v1/nwro-e2eo/resources/nsr-123",
            "result": "000000",
            "sequenceNo": "12345"
        }

+ Response 200 (application/json)

        {
            "location": "/v1/e2eo-nwro/notifications/hoge-id", 
            "responseHeader": {
                "processCode": "000000", 
                "processID": "xx1123456789012", 
                "receivedDate": "2015/09/10 12:34:56", 
                "sequenceNo": "54321"
            }
        }

# Group <リソース>

## リソース【リソースID指定あり】 [/vi/nwro/resources/{id}]

### リソース変更およびリソース変更通知結果 [PUT]
+ Response 200 (application/json)

### リソース削除 [DELETE]
+ Response 200 (application/json)

## リソース結果通知 [/v1/e2eo/resources/{id}]

NWROからE2EOに対してリソースの変更および結果通知を行う。
リソースの変更通知は警報が対象であり、警報通知先登録が行われていなければ通知されない。
リソースの結果通知は予約生成、生成、変更、削除の結果通知を行う。

### リソース予約生成、生成の登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列

# Group <警報>

## 警報【リソースID指定なし】 [/v1/nwro/alarms]

### 警報通知先登録 [POST]

警報の通知先を登録する

+ question (string) - The question

+ Request (application/json)

        {
        "question": "Favorite programming language?"
        }

+ Response 200 (application/json)

    + Headers
    
            Location: /questions/1
    
    + Body
    
            {
                "question": "Favorite programming language?",
                "is": "Ruby"
            }

## 警報【リソースID指定あり】 [/vi/nwro/alarms/{id}]

### 警報通知先照会 [GET]
+ Response 200 (application/json)

### 警報通知先変更 [PUT]
+ Response 200 (application/json)

### 警報通知先削除 [DELETE]
+ Response 200 (application/json)

## 警報通知 [/v1/e2eo/alarms/{id}]

### 警報通知先登録登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列



