FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# E2EO

E2EO-NWRO REST API インターフェース

# Group <カタログ>

## カタログ【リソースID指定なし】 [/v1/nwro/catalogues]

### カタログ登録 [POST]

カタログ登録する

+ NSD(object) - NSDオブジェクトを渡す。

+ Request (application/json)

        {
        "question": "Favorite programming language?"
        }

+ Response 200 (application/json)

    + Headers
    
            Location: /questions/1
    
    + Body
    
            {
                "question": "Favorite programming language?",
                "is": "Ruby"
            }

## カタログ【リソースID指定あり】 [/vi/nwro/catalogues/{id}]

### カタログ変更 [PUT]
+ Response 200 (application/json)

### カタログ削除 [DELETE]
+ Response 200 (application/json)

## カタログ結果通知 [/v1/e2eo/catalogues/{id}]

### カタログ登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列


# Group <リソース>

## リソース【リソースID指定なし】 [/v1/nwro/resources]

### リソース予約 [POST]

リソースを予約する。
cf. "NFVIFA(15)000435r10_IFA013_NS_Lifecycle_Mgmt_Operations.docx"

+ 必要パラメータ: NSR

+ Request (application/json)

        {
            "asyncNotificationLocation": "/v1/e2eo-nwro/notifications", 
            "flavourId": "flvour-789", 
            "nsdId": "ns-001_v1.0", 
            "requestHeader": {
                "apiKey": "#aea57sjas6vsst4jwjol", 
                "functionType": 10, 
                "senderSystemId": "e2eo", 
                "sequenceNo": "12345"
            }, 
            "serviceAccessPoints": {
                "cp-03": "NMS=wim-01/EMS=ems/ME-ID=クラスタ番号+leafSW番号/rack=1/shelf=1/slot=1/subslot=1", 
                "cp-10": "NMS=wim-01/EMS=ems/ME-ID=クラスタ番号+leafSW番号/rack=1/shelf=1/slot=2/subslot=1"
            }
        }

+ Response 200 (application/json)


    + Body
    
            {
                "responseHeader": {
                "processCode": "000000",
                "processID": "xx1123456789012",
                "receivedDate": "2015/09/10 12:34:56",
                "sequenceNo": "12345"
                }
            }


## リソース【リソースID指定あり】 [/vi/nwro/resources/{id}]

### リソース照会 [GET]

指定したリソースの情報を参照する。

+ Parameters
    + id: NSR001 (string) - NSRを指定する。
    ++ Default: NSR99
    
+ Response 200 (application/json)

        {
            "connection_point": [
                {
                    "Id": "CP11",
                    "type": "virtual port"
                },
                {
                    "Id": "CP21",
                    "type": "virtual port"
                }
            ],
            "id": "NSR-001",
            "requestHeader": {
                "apiKey": "#aea57sjas6vsst4jwjol",
                "functionType": 1,
                "senderSystemId": "e2eo",
                "sequenceNo": "12345"
            },
            "status": "予約",
            "vendor": "OCN",
            "version": "1.1",
            "vlr": [
                {
                    "connection": [
                        {
                            "id": "CP11"
                        },
                        {
                            "id": "CP21"
                        }
                    ],
                    "id": "VL1"
                }
            ],
            "vnffgr": [
                {
                    "connection_point": [
                        {
                            "id": "CP21"
                        },
                        {
                            "id": "CP22"
                        }
                    ],
                    "id": "VNFFG1",
                    "vendor": "OCN",
                    "version": "v1.1"
                }
            ]
        }

        
### リソース変更およびリソース変更通知結果 [PUT]
+ Response 200 (application/json)

### リソース削除 [DELETE]
+ Response 200 (application/json)

## リソース結果通知 [/v1/e2eo/resources/{id}]

NWROからE2EOに対してリソースの変更および結果通知を行う。
リソースの変更通知は警報が対象であり、警報通知先登録が行われていなければ通知されない。
リソースの結果通知は予約生成、生成、変更、削除の結果通知を行う。

### リソース予約生成、生成の登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列

# Group <警報>

## 警報【リソースID指定なし】 [/v1/nwro/alarms]

### 警報通知先登録 [POST]

警報の通知先を登録する

+ question (string) - The question

+ Request (application/json)

        {
        "question": "Favorite programming language?"
        }

+ Response 200 (application/json)

    + Headers
    
            Location: /questions/1
    
    + Body
    
            {
                "question": "Favorite programming language?",
                "is": "Ruby"
            }

## 警報【リソースID指定あり】 [/vi/nwro/alarms/{id}]

### 警報通知先照会 [GET]
+ Response 200 (application/json)

### 警報通知先変更 [PUT]
+ Response 200 (application/json)

### 警報通知先削除 [DELETE]
+ Response 200 (application/json)

## 警報通知 [/v1/e2eo/alarms/{id}]

### 警報通知先登録登録・変更・削除結果通知 [PUT]
+ Response 200 (application/json)

+ Parameters
    + id: `NSD-001` ( string) ... リソースID、型は文字列



